restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include(
        ("restaurantKitchenService.urls", "restaurant"),
        namespace="restaurant")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurantKitchenService/urls.py
from django.urls import path

from restaurantKitchenService.views import (
    AllDishView,
    AllCookerView,
    AllDishTypesView,
    DishView,
    DishTypeView,
    index,
    CreateDishView,
    UpdateDishView,
    DeleteDishView,
    CreateDishTypeView,
    UpdateDishTypeView,
    DeleteDishTypeView,
    DetailCookerView,
    CreateCookerView, UpdateCookerView)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", AllDishView.as_view(), name="dishes"),
    path("dishes/create/", CreateDishView.as_view(), name="create_dish"),
    path(
        "dishes/<int:pk>/update/",
        UpdateDishView.as_view(),
        name="update_dish"),
    path(
        "dishes/<int:pk>/delete/",
        DeleteDishView.as_view(),
        name="delete_dish"),
    path("cookers/", AllCookerView.as_view(), name="cookers"),
    path(
        "cookers/<int:pk>/",
        DetailCookerView.as_view(),
        name="cookers_detail"),
    path("cookers/create/", CreateCookerView.as_view(), name="cookers_create"),
    path("coockers/<int:pk>/update", UpdateCookerView.as_view(), name="cookers_update"),
    path("dishesTypes/", AllDishTypesView.as_view(), name="dishTypes"),
    path(
        "dishesTypes/create/",
        CreateDishTypeView.as_view(),
        name="dishTypes_create"),
    path(
        "dishesTypes/<int:pk>/update/",
        UpdateDishTypeView.as_view(),
        name="dishTypes_update"),
    path(
        "dishesTypes/<int:pk>/delete/",
        DeleteDishTypeView.as_view(),
        name="dishTypes_delete"),
    path("dishes/<int:pk>/", DishView.as_view(), name="dish_view"),
    path("dishesTypes/<int:pk>/",
         DishTypeView.as_view(), name="dishTypes_detail"),
]

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <form method="POST" action="{% url 'logout' %}">
      {% csrf_token %}
      <button class="button">Logout</button>
    </form>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>

  <li class="list-group-item"><a href="{% url 'restaurant:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:dishes' %}">All dishes</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:cookers' %}">All coockers</a></li>
  <li class="list-group-item"><a href="{% url 'restaurant:dishTypes' %}">All dish types</a></li>
</ul>