restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("", include(
        ("restaurantKitchenService.urls", "restaurant"),
        namespace="restaurant")),
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurantKitchenService/urls.py
from django.urls import path

from restaurantKitchenService.views import (
    AllDishView,
    AllCookerView,
    AllDishTypesView,
    DishView,
    DishTypeView,
    index,
    CreateDishView,
    UpdateDishView,
    DeleteDishView,
    CreateDishTypeView,
    UpdateDishTypeView,
    DeleteDishTypeView,
    DetailCookerView,
    CreateCookerView, UpdateCookerView)

urlpatterns = [
    path("", index, name="index"),
    path("dishes/", AllDishView.as_view(), name="dishes"),
    path("dishes/create/", CreateDishView.as_view(), name="create_dish"),
    path(
        "dishes/<int:pk>/update/",
        UpdateDishView.as_view(),
        name="update_dish"),
    path(
        "dishes/<int:pk>/delete/",
        DeleteDishView.as_view(),
        name="delete_dish"),
    path("cookers/", AllCookerView.as_view(), name="cookers"),
    path(
        "cookers/<int:pk>/",
        DetailCookerView.as_view(),
        name="cookers_detail"),
    path("cookers/create/", CreateCookerView.as_view(), name="cookers_create"),
    path("coockers/<int:pk>/update", UpdateCookerView.as_view(), name="cookers_update"),
    path("dishesTypes/", AllDishTypesView.as_view(), name="dishTypes"),
    path(
        "dishesTypes/create/",
        CreateDishTypeView.as_view(),
        name="dishTypes_create"),
    path(
        "dishesTypes/<int:pk>/update/",
        UpdateDishTypeView.as_view(),
        name="dishTypes_update"),
    path(
        "dishesTypes/<int:pk>/delete/",
        DeleteDishTypeView.as_view(),
        name="dishTypes_delete"),
    path("dishes/<int:pk>/", DishView.as_view(), name="dish_view"),
    path("dishesTypes/<int:pk>/",
         DishTypeView.as_view(), name="dishTypes_detail"),
]

restaurantKitchenService/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class DishType(models.Model):
    name = models.CharField(max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:dishTypes_detail", kwargs={"pk": self.pk})


class Cook(AbstractUser):
    year_of_expirience = models.IntegerField(default=0)

    class Meta:
        verbose_name = "cooker"
        verbose_name_plural = "cookers"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("restaurant:cookers_detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=65)
    description = models.TextField()
    price = models.DecimalField(max_digits=7, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE, related_name="dish_type")
    cooks = models.ManyToManyField(Cook, related_name="cooks")

    def get_absolute_url(self):
        return reverse("restaurant:dish_view", kwargs={"pk": self.pk})

restaurantKitchenService/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from restaurantKitchenService.models import DishType, Cook, Dish


class DishTypeCreationForm(forms.ModelForm):
    class Meta:
        model = DishType
        fields = "__all__"


class CookersCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "year_of_expirience",
            "first_name",
            "last_name"
        )

    def clean(self):
        super().clean()
        year_of_expirience = self.cleaned_data.get("year_of_expirience")
        if year_of_expirience > 80:
            self._errors["year_of_expirience"] = self.error_class(["Year of expirience is to big "])

        return self.cleaned_data


class DishCreationForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(required=False, max_length=255)


class CookSearchForm(forms.Form):
    username = forms.CharField(required=False, max_length=255)


class DishSearchForm(forms.Form):
    name = forms.CharField(required=False, max_length=255)

restaurantKitchenService/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic

from restaurantKitchenService.forms import (
    DishCreationForm,
    CookersCreationForm,
    DishTypeCreationForm,
    DishSearchForm,
    CookSearchForm,
    DishTypeSearchForm)
from restaurantKitchenService.models import DishType, Cook, Dish


class IndexView(generic.View):
    templates = "restaurantKitchenService/index.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        num_dishes = Dish.objects.count()

        num_visits = self.request.session.get("num_visits", 0)
        self.request.session["num_visits"] = num_visits + 1

        context = {
            "num_dishes": num_dishes,
            "num_visits": self.request.session["num_visits"],
        }

        return context


@login_required
def index(request):
    num_dishes = Dish.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_dishes": num_dishes,
        "num_visits": request.session["num_visits"],
    }

    return render(
        request,
        "restaurantKitchenService/index.html",
        context=context)


class AllDishView(generic.ListView):
    model = Dish
    context_object_name = "dishes"
    paginate_by = 5
    template_name = "restaurantKitchenService/dish_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = DishSearchForm()
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return Dish.objects.filter(name__icontains=name)
        return Dish.objects.all()


class DishView(generic.DetailView):
    model = Dish
    context_object_name = "dish"
    template_name = "restaurantKitchenService/dish_detail.html"


class CreateDishView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishCreationForm
    success_url = reverse_lazy("restaurant:dishes")


class UpdateDishView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishCreationForm
    success_url = reverse_lazy("restaurant:dishes")


class DeleteDishView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dishes")


class AllCookerView(generic.ListView):
    model = Cook
    context_object_name = "cookers"
    paginate_by = 5
    template_name = "restaurantKitchenService/cookers_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = CookSearchForm()
        return context

    def get_queryset(self):
        username = self.request.GET.get("username")
        if username:
            return Cook.objects.filter(username__icontains=username)
        return Cook.objects.all()


class CreateCookerView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookersCreationForm


class DetailCookerView(generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("cooks")


class UpdateCookerView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    form_class = CookersCreationForm


class AllDishTypesView(generic.ListView):
    model = DishType
    context_object_name = "dishTypes"
    paginate_by = 5
    template_name = "restaurantKitchenService/dishType_list.html"

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context["search_form"] = DishTypeSearchForm()
        return context

    def get_queryset(self):
        name = self.request.GET.get("name")
        if name:
            return DishType.objects.filter(name__icontains=name)
        return DishType.objects.all()


class DishTypeView(generic.DetailView):
    model = DishType
    context_object_name = "dish"
    template_name = "restaurantKitchenService/dishType_detail.html"


class CreateDishTypeView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    form_class = DishTypeCreationForm
    success_url = reverse_lazy("restaurant:dishTypes")


class UpdateDishTypeView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    form_class = DishTypeCreationForm
    success_url = reverse_lazy("restaurant:dishTypes")


class DeleteDishTypeView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("restaurant:dishTypes")

templates/restaurantKitchenService/cook_detail.html
{% extends "base.html" %}

{% block content %}
    <a href="{% url 'restaurant:cookers_update' pk=cook.id%}" class="top-right-position btn btn-primary">Обновити інформацію про себе</a>
  <h1>Username : {{ cook.username }}</h1>
  <h2>First name: <b>{{ cook.first_name }}</b></h2>
  <h2>Last name: <b>{{ cook.last_name }}</b></h2>
  <h4>Years of expirience: <b>{{ cook.year_of_expirience }}</b></h4>
<br>
  <h3>List of coocked dishes</h3>
  <ul>
    {% for dish in cook.cooks.all %}
      <li><a href="{{ dish.get_absolute_url }}">{{ dish.name }}</a></li>
    {% endfor %}
  </ul>
{% endblock %}

templates/restaurantKitchenService/cook_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Cookers</h1>
<form action="" method="post" novalidate>
    {{ form.error }}
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurantKitchenService/cookers_list.html
{% extends "base.html" %}

{% block content %}
  <form method="get" action="">
    {{ search_form }}
  </form>
  <a href="{% url 'restaurant:cookers_create' %}" class="top-right-position btn btn-primary">створити кухаря </a>
  <ul>
  {% for cooker in cookers %}
    <li>{{ cooker.username }}</li>
  {% endfor %}
  </ul>
{% endblock %}

templates/restaurantKitchenService/dishType_detail.html
{% extends "base.html" %}

{% block content %}
    <p>{{ dish.name }}</p>
    <p>
      <a href="{% url 'restaurant:dishTypes_update' pk=dish.id %}" class="btn btn-primary">Редагувати</a>
      <a href="{% url 'restaurant:dishTypes_delete' pk=dish.id %}" class="btn btn-danger">Вилучити</a>
    </p>
    All dish with this type :
    <ul>
    {% for dis in dish.dish_type.all %}
      <li>
        <a href="{{ dis.get_absolute_url }}">{{ dis.name }}</a>
      </li>
    {% endfor %}
    </ul>
{% endblock %}

templates/restaurantKitchenService/dishType_list.html
{% extends "base.html" %}

{% block content %}
  <form method="get" action="">
    {{ search_form }}
  </form>
  <a href="{% url 'restaurant:dishTypes_create' %}" class="top-right-position btn btn-primary">створити вид страв </a>
  {% for dish in dishTypes %}
    <p>{{ dish }} - <a href="{{ dish.get_absolute_url }}"> Детальний огляд</a></p>
  {% endfor %}
{% endblock %}

templates/restaurantKitchenService/dish_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurantKitchenService/dish_detail.html
{% extends "base.html" %}

{% block content %}
    <div class="main-info">
      <div class="name">{{ dish.name }}</div>
      <div class="type">{{ dish.dish_type }}</div>
      <div class="price">${{ dish.price }}</div>
    </div>

  <p>The man who coocked it:</p>
  {% for coocker in dish.cooks.all %}
    {{ coocker.username }} | {{ coocker.year_of_expirience }}
  {% endfor %}
  <p><a href="{% url 'restaurant:update_dish' pk=dish.id %}" class="btn btn-primary">Редагувати</a>
    <a href="{% url 'restaurant:delete_dish' pk=dish.id %}" class="btn btn-danger">Вилучити</a></p>
{% endblock %}

templates/restaurantKitchenService/dish_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish</h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurantKitchenService/dish_list.html
{% extends "base.html" %}

{% block content %}
  <form method="get" action="">
    {{ search_form }}
  </form>
  <a href="{% url 'restaurant:create_dish' %}" class="top-right-position btn btn-primary">створити страву </a>
  {% for dish in dishes %}
    <p>{{ dish.name }} - <a href="{{ dish.get_absolute_url }}">Детальний огляд</a></p>
  {% endfor %}
{% endblock %}

templates/restaurantKitchenService/dishtype_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <h1>Delete dish type?</h1>
  <form action="" method="post">
    {% csrf_token %}

    <input type="submit" value="Yes" class="btn btn-danger">
  </form>
{% endblock %}

templates/restaurantKitchenService/dishtype_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Dish type</h1>
<form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form }}

    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/restaurantKitchenService/index.html
{% extends "base.html" %}

{% block content %}
  Total visits of this page is : {{ num_visits }}

  You can order {{ num_dishes }} diferent dish
{% endblock %}